### ISSUE TITLE
docker-compose-test.yml does not exist

### ISSUE THREAD

**Issue by sirockin** [mjhea0/node-docker-api#2]
The end of readme.md reads:

----

Run unit and integration tests:
```
$ export NODE_ENV=test
$ docker-compose up -d
$ docker-compose -f docker-compose-test.yml run users-service npm test
$ docker-compose -f docker-compose-test.yml run locations-service npm test
```
----
Running either of the last two commands results in a file not found error as docker-compose-test.yml does not exist.

**Comment by mjhea0** [comment]
just updated the readme. thanks!
